The ``100-matrix_mul`` doctest
==================================

Using ``matrix_multiplication``
--------------------------

Import function from module:
	>>> matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Normal case with two matrices:
	>>> matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
	array([[ 7, 10],
       	       [15, 22]])

Test one argument:
	>>> matrix_mul()
	Traceback (most recent call last):
	TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

Test empty matrices:
	>>> matrix_mul([], [])
	False

Test just empty m_b:
	>>> matrix_mul([[1, 2], [3, 4]], [])
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

Test empty m_a[[]]:
	>>> matrix_mul([[]], [[4, 5], [6, 7]])
	Traceback (most recent call last):
	ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

Test empty m_b[[]]:
	>>> matrix_mul([[1, 2], [3, 4]], [[]])
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

Test different lengths of m_a:
	>>> matrix_mul([[1, 2, 3], [4, 5]], [[6, 7, 8], [8, 9, 10]])
	Traceback (most recent call last):
	ValueError: setting an array element with a sequence.

Test different lengths of m_b:
	>>> matrix_mul([[1, 2, 3], [4, 5, 6]], [[5, 6, 7], [8, 9]])
	Traceback (most recent call last):
	ValueError: setting an array element with a sequence.

Test 1st arg string:
	>>> matrix_mul("Holberton", [[4, 5], [6, 7]])
	Traceback (most recent call last):
	TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U9') dtype('<U9') dtype('<U9')

Test 2nd arg string:
        >>> matrix_mul([[5, 6], [7, 8]], "Holberton")
	Traceback (most recent call last):
	TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U9') dtype('<U9') dtype('<U9')

Test different number of matrix:
	>>> matrix_mul([[1, 2], [3, 4]], [[5, 6]])
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

Test list of string m_a:
	>>> matrix_mul([["Holberton", "School"], ["is", "cool"]], [[1, 2], [3, 4]])
	Traceback (most recent call last):
	ValueError: data type must provide an itemsize

Test list of string m_b:
	>>> matrix_mul([[1, 2], [3, 4]], [["Holberton", "School"], ["is", "cool"]])
	Traceback (most recent call last):
	ValueError: data type must provide an itemsize

Test list of ints for m_a:
	>>> matrix_mul([1, 2, 3, 4], [[1, 2], [3, 4]])
	Traceback (most recent call last):
	ValueError: shapes (4,) and (2,2) not aligned: 4 (dim 0) != 2 (dim 0)

Test list of ints for m_b:
	>>> matrix_mul([[1, 2], [3, 4]], [1, 2, 3, 4])
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)
